version: 2
jobs:
  build:
    docker:
      - image: osteele/circleci-node:0.0.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          - v2-dependencies-
      - run:
          name: Install node dependencies
          command: yarn install
      - save_cache:
          key: v2-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: yarn build
      - deploy:
          name: Deploy
          command: |
            aws s3 sync public s3://minsky-bio.web/ --delete
            aws cloudfront create-invalidation --distribution-id E2954NPTLAM2GP --paths '/*' --output text
