version: "2.1"

services:
  gatsby:
      build: .
      ports:
        - 8000:8000
      volumes:
        - ./config:/app/config
        - ./content:/app/content
        - ./src:/app/src
        - ./static:/app/static
      entrypoint: ["sh", "-c"]
      command: ["gatsby develop -H 0.0.0.0"]
